pool:
  vmImage: vs2017-win2016
variables:
  ProjectName: 'PoshProject'

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: ./psake.ps1

- task: ArchiveFiles@2
  displayName: 'Archive $(ProjectName)'
  inputs:
    rootFolderOrFile: '$(ProjectName)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Build'
  inputs:
    ArtifactName: Build

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/Tests/result/$(ProjectName)Tests.xml'
